### ISSUE TITLE
Application default namespace properties missing

### ISSUE THREAD

**Issue by riha** [robinhultman/generator-biztalk#1]
When creating new BT project the default namespace in the application properties of the project file isn't set. This should be the same as the project name. As this is the default namespace prefix for all subsequent  created files the result is otherwise that one has to add the namespace each time or that they are created without a namespace prefix.

I created a BizTalk 2013 R2 project for replicating this but I guess this is valid for all project types.

**Comment by robinhultman** [comment]
Same as issue #2
